### PR TITLE
update deps, tweaked config, added yarn pkg, and setup distribution w/ docs - 091817

### PR DESCRIPTION
**Pull request by 1-14x0r**
- updated React dependencies
- add support to use foreman to run project
- merged [PR](https://github.com/csepulv/electron-with-create-react-app/pull/2) to use `npm start` not 'npm run dev'
- added .env configuration file
- suppress browser when starting; only run in electron
- moved port from package.json to .env
- add support to use yarn package manager
- added electron-builder for package distribution
- updated documentation on how create from ground up

### CODE REVIEW

**Comment by csepulv** [comment]
I appreciate your interest in the project. I'll go through the PR in a few days, but as a few initial notes:
* updating to latest React, Electron makes complete sense
* there was already a request for `npm start` instead of `npm run dev`. You can take a look at this [PR](https://github.com/csepulv/electron-with-create-react-app/pull/2), which was merged into a branch. (also referenced on project README)

It seems you are actively making changes and adding them to the PR. Can you explain your goals a bit?

**Comment by 1-14x0r** [comment]
I am working getting your fantastic code packaging and distributing with electron-builder.. which is turning into not a small feat. I also have been trying to update and put in more detailed step by step process for this, based on your article.

**Comment by csepulv** [comment]
I suggest you look at this [issue](https://github.com/csepulv/electron-with-create-react-app/issues/3).  Another user did this, in their own fork. The details are in the referenced issue.

**Comment by 1-14x0r** [comment]
Thanx for the link i will try to recreate and build using that repo and compare.. i was also able to get a nice build working from this [repo ](https://github.com/kitze/react-electron-example). Its similiar but is missing some things that i think this repo is doing better; IE naming conventions and config.

**Comment by 1-14x0r** [comment]
also check out this [repo ](https://github.com/1-14x0r/react-electron-example) which uses auto update. It works the same as this project, however i was able to greatly simplify it. Thanx!

**Comment by csepulv** [comment]
as a note, I updated to latest react and electron

**Pull request closed without merging**
